version: "2.4"
services:
  products:
    extends:
      service: spring-boot
      file: docker-compose-base.yml
    environment:
      - APP_SERVICE_NAME=products
      - AXON_AXONSERVER_SERVERS=axon:8124
    depends_on:
      - eureka
      - gateway

  eureka:
    extends:
      service: spring-boot
      file: docker-compose-base.yml
    environment:
      - SERVER_PORT=8200
      - APP_SERVICE_NAME=eureka
      - EUREKA_INSTANCE_HOSTNAME=eureka
    ports:
      - "8200:8200"

  gateway:
    extends:
      service: spring-boot
      file: docker-compose-base.yml
    environment:
      - SERVER_PORT=8080
      - APP_SERVICE_NAME=gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka

  axon:
    image: axoniq/axonserver:4.5.9-jdk-17-dev
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - ./data/axon/data:/axonserver/data
      - ./data/axon/events:/axonserver/events
      - ./data/axon/config:/axonserver/config
