version: "2.4"
services:
  spring-boot:
    working_dir: /app
    image: gradle:7.3.0-jdk17
    command: 'sh ./run.sh'
    volumes:
      - ./run.sh:/app/run.sh
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      - ./products:/app/products
      - ./orders:/app/orders
      - ./eureka:/app/eureka
      - ./gateway:/app/gateway
      - ./domain:/app/domain
    environment:
      - _JAVA_OPTIONS=-Xmx256m
      - EUREKA_URI=http://eureka:8200/eureka/
      - SERVER_PORT=8080
