version: "2.4"
services:
  spring-boot:
    working_dir: /app
    image: gradle:7.3.0-jdk17
    command: 'sh ./run.sh'
    volumes:
      - ./run.sh:/app/run.sh
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      - ./products:/app/products
      - ./eureka:/app/eureka
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - EUREKA_URI=http://eureka:8200/eureka/
      - SERVER_PORT=0
