spring:
  application:
    name: products-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    statusPageUrlPath: /actuator
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off
